services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sd1991308
    volumes:
      - ./mysqldb/_data:/var/lib/mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    restart: unless-stopped # 容器在意外停止后自动重启
    networks:
      - aisnknet

  aisnk:
    image: aisnk:latest # 使用的镜像
    container_name: aisnk # 容器名称
    ports:
      - "3000:3000" # 将宿主机的 3000 端口映射到容器的 3000 端口
    volumes:
      - ./aisnk.com.key:/app/aisnk.com.key
      - ./aisnk.com.pem:/app/aisnk.com.pem
      - ./uploads:/app/uploads # 将宿主机的目录挂载到容器
      - ./.env:/app/.env # 将当前目录下的 .env 文件挂载到容器的 /app 目录
    restart: unless-stopped # 容器在意外停止后自动重启
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - mysql
    networks:
      - aisnknet

networks:
  aisnknet:
    driver: bridge # 创建一个桥接网络，允许容器之间通过名称通信
